export type RiskLevel = "low" | "medium" | "high";

export interface ContentLane {
  description: string;
  exampleHooks: string[];
  id: string;
  targetDurationSeconds: number;
}

export interface TopicCandidate {
  laneId: string;
  noveltyScore: number;
  riskLevel: RiskLevel;
  seedQuestion: string;
  titleAngle: string;
}

export interface TopicHistoryEntry {
  laneId: string;
  titleAngle: string;
  seedQuestion: string;
  runId: string;
  date: string;
}

export interface ResearchClaim {
  claim: string;
  confidence: "tentative" | "supported" | "strong";
  sourceLabels: string[];
}

export interface ResearchPack {
  claims: ResearchClaim[];
  summary: string;
  topic: string;
}

export interface ScriptBeat {
  beatIndex: number;
  narration: string;
  visualIntent: string;
}

export interface PublishMeta {
  /** SEO-optimized YouTube title (max 100 chars, not the hook) */
  youtubeTitle: string;
  /** Formatted YouTube description — summary, key takeaways, CTA */
  youtubeDescription: string;
  /** Topic-specific tags for YouTube search (5-10 tags) */
  topicTags: string[];
  /** Topic-specific hashtags for TikTok/Shorts (3-5, including #) */
  topicHashtags: string[];
}

export interface ShortScript {
  callToAction: string;
  hook: string;
  payoff: string;
  beats: ScriptBeat[];
  totalDurationSeconds: number;
  /** Platform-optimized publishing metadata (generated by LLM) */
  publishMeta?: PublishMeta;
}

export interface ScenePlan {
  captions: string[];
  prompt: string;
  sceneIndex: number;
  seconds: number;
}

export interface GenSecAssessment {
  blockedReasons: string[];
  disclosureRequired: boolean;
  riskLevel: RiskLevel;
  safeToAutoPublish: boolean;
}

export type PublishPlatform = "youtube" | "tiktok";

export interface PublishPackage {
  description: string;
  disclosureRequired: boolean;
  platforms: PublishPlatform[];
  scheduledSlot: string;
  tags: string[];
  title: string;
}

export interface StockClip {
  id: number;
  url: string;
  width: number;
  height: number;
  duration: number;
  localPath?: string;
  searchQuery: string;
}

export interface SubtitleEntry {
  start: number;
  end: number;
  text: string;
}

export interface WordTiming {
  text: string;
  startMs: number;
  endMs: number;
}

export interface VoiceoverResult {
  audioPath: string;
  durationSeconds: number;
  subtitles: SubtitleEntry[];
  wordTimings: WordTiming[];
}

export interface ScenePlanWithKeywords extends ScenePlan {
  searchKeywords: string[];
  /** Plain-English description of the ideal stock clip for this scene */
  visualDescription: string;
}

export type ApprovalStatus = "pending" | "approved" | "revisions_requested" | "rejected";

export interface ApprovalGateRecord {
  gateId: string;
  label: string;
  status: ApprovalStatus;
  required: boolean;
  updatedAt: string;
  reviewer: string | null;
  notes: string | null;
  artifactPath: string;
}

export interface StoryboardScene {
  sceneIndex: number;
  title: string;
  narration: string;
  storyPurpose: string;
  visualIntent: string;
  camera: string;
  composition: string;
  motion: string;
  caption: string;
  seconds: number;
  continuityNotes: string[];
  assetNeeds: string[];
  /** Stock-photo preview matching what stock-footage stage will likely fetch. */
  sketchFramePath: string;
  /** Optional AI-generated concept-art sketch for creative reference. */
  aiSketchPath?: string;
}

export interface StoryboardDeck {
  runId: string;
  brandId: string;
  displayName: string;
  hook: string;
  payoff: string;
  scenes: StoryboardScene[];
  generatedAt: string;
}

export interface AssetManifest {
  version: number;
  generatedAt: string;
  categories: {
    storyboardTemplates: string[];
    captionThemes: string[];
    motionPresets: string[];
    textures: string[];
    transitions: string[];
    musicBeds: string[];
    sfx: string[];
  };
}

export interface ClipCandidate {
  video: { id: number; width: number; height: number; duration: number; tags: unknown[] };
  file: { link: string; width: number | null; height: number | null; quality: string };
  matchedKeyword: string;
}

export interface ScoredCandidate extends ClipCandidate {
  score: number;
}

/**
 * Mutable accumulator passed through pipeline stages.
 * Each stage reads what it needs and writes its output here.
 */
export interface PipelineState {
  lane?: ContentLane;
  topic?: TopicCandidate;
  research?: ResearchPack;
  script?: ShortScript;
  scenes?: ScenePlanWithKeywords[];
  storyboard?: StoryboardDeck;
  approvals?: Record<string, ApprovalGateRecord>;
  assetManifest?: AssetManifest;
  halted?: boolean;
  haltReason?: string;
  haltedGateId?: string;
  voiceover?: VoiceoverResult;
  clips?: StockClip[];
  rawVideoPath?: string;
  outputVideoPath?: string;
  uploadResults?: import("./interfaces/uploader.js").UploadResult[];
}
